apiVersion: v1
kind: Secret
metadata:
  name: secret-test
type: Opaque
stringData:
  config.yaml: |-
    username: ravindra
    password: password

Generating Secret Based on Generic - Literal Value
kubectl create secret generic  firstsecret --from-literal=dbpassword=mypassword123

Generating Secret Based on Generic - File
kubectl create secret generic  secondsecret --from-file=./credentials.txt    
