apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: frontend
    image: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: mypod-storage
  volumes:
  - name: mypod-storage
    persistentVolumeClaim:
      claimName: managed-disk         
