apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 12Gi
