apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - gke-labs-labs-k8s-labs-62199ce4-r3c8dsdsd
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
    
    #It will still create pods if it not able to match the labels i.e hostname
