apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
spec:  
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: NotIn
            values:
            - dev
        topologyKey: kubernetes.io/hostname
            
  containers:
  - name: pod-affinity
    image: k8s.gcr.io/pause:2.0
    
    
    #It will not create the pod where the pod having lables i.e app=dev
